services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pucesi-backend
    ports:
      - "4001:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - "C:/Users/adria/OneDrive/Desktop/INTEGRACION CURRICULAR/BACKUPS & LOGS/LOGS:/app/logs"
      - "C:/Users/adria/OneDrive/Desktop/INTEGRACION CURRICULAR/BACKUPS & LOGS/BACKUP:/app/backups"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: pucesi-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pucesi_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pucesi_pgdata:
